### ISSUE TITLE
Nim wordfile

### ISSUE THREAD

**Issue by sigzero** [IDMComputerSolutions/wordfiles#29]
Attached you will find the Nim word file and a test file as well.

The thing to note is that UE cannot support both types of comments that Nim supports.

Single line comments start with a "#". With the following being a comment:

`# This is a comment`

Multi-line comments are in the form of "#[   ]#". With the following being a comment:

`#[`
     `This is is a multi-line comment in Nim`
`]#`

I have only added support for the single-line since I was told the multi-line was not doable with the current wordfile syntax.

You can do what you will with it.  : )

[Nim.zip](https://github.com/IDMComputerSolutions/wordfiles/files/4725675/Nim.zip)

**Comment by bschwenk** [comment]
@sigzero looks like we added this and forgot to close it. Thanks for your contribution!
