### ISSUE TITLE
Request for FreePascal wordfile

### ISSUE THREAD

**Issue by astr0wiz** [IDMComputerSolutions/wordfiles#30]
I've created it, but since I don't have permissions to push a branch, I thought I'd submit it here (extension 'txt' to allow attachment).  
[freepascal.txt](https://github.com/IDMComputerSolutions/wordfiles/files/4991731/freepascal.txt)

**Comment by bschwenk** [comment]
@astr0wiz thanks for passing this along! Are you saying you tried to generate a PR but were unable to? You should be able to submit a PR. (We'll review the wordfile internally and add to the repository assuming it all checks out.)

**Comment by bschwenk** [comment]
@astr0wiz looks like the wordfile contains the following duplicate keywords:

1. break -> in /C1
  break -> in /C2
2. continue -> in /C1
  continue -> in /C2
3. dispose -> in /C1
  dispose -> in /C3
4. false -> in /C1
  false -> in /C3
5. new -> in /C1
  new -> in /C3
6. reintroduce -> in /C1
  reintroduce -> in /C2
7. true -> in /C1
  true -> in /C3
8. read -> in /C2
  read -> in /C3
9. write -> in /C2
  write -> in /C3

**Comment by astr0wiz** [comment]
Thanks for checking.  I've cleaned it up and here it is:
[freepascal.txt](https://github.com/IDMComputerSolutions/wordfiles/files/5131642/freepascal.txt)

**Comment by bschwenk** [comment]
Thanks @astr0wiz! Added.
