### ISSUE TITLE
can't make my own ue-theme.uew

### ISSUE THREAD

**Issue by bluelovers** [IDMComputerSolutions/wordfiles#4]
can't make my own ue-theme.uew

the xml setting keeep overwrite on ue-theme

https://github.com/bluelovers/wordfiles/blob/wordfiles/ue-theme.uew

**Comment by bluelovers** [comment]
update
--------

ultraedit only support CRLF, not support LF
so it will make wordfile and uep.ini error

**Comment by A-Mofi** [comment]
What do you think about https://github.com/A-Mofi/wordfiles/blob/master/ue-theme.uew - my version of a wordfile for *.ue-theme files for UC, UE, UES which is based on your wordfile, but with re-organized color groups, modified function strings and additional words (from UC theme file, and explicitly listing all identifiers)?
