### ISSUE TITLE
SCSS dosn't work

### ISSUE THREAD

**Issue by ReneMuetti** [IDMComputerSolutions/wordfiles#7]
hello

I have downloaded and installed the Word file. It is also offered me the menu. But if I open a SCSS file, it is not loaded. I have to change any file manually. This is not pleasant - I have been working with many files

**Comment by bschwenk** [comment]
Rene,

Did you go over the checks listed here? 

http://www.ultraedit.com/support/tutorials_power_tips/ultraedit/add_a_wordfile.html#troubleshooting

Let us know if you still can't get this to work.

Thanks,

Ben

**Comment by ReneMuetti** [comment]
hello
Exactly it was ....

But what I do not understand:
1.) Why not UTF-8 but ANSI / ASCII
2.) Why only DOS

They're both basically "dead" systems - and UTF-8 has also not the sign confusion result. It can be used on any system the same as it is a universal character set. ANSI / ASCII only makes trouble

Also why it is absolutely necessary as DOS line endings to me not obvious. It should not be a challenge basically to recognize the line end mark accordingly. You have quite capable developers. This should be no cause "Large".

An otherwise - thank you
